"""empty message

Revision ID: 3394654f4780
Revises: 23c49602b4ca
Create Date: 2015-01-30 14:49:18.237825

"""

# revision identifiers, used by Alembic.
revision = '3394654f4780'
down_revision = '23c49602b4ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', postgresql.UUID(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'results', sa.Column('query_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('result_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'results', 'result_url')
    op.drop_column(u'results', 'query_id')
    op.drop_table('queries')
    ### end Alembic commands ###
