"""empty message

Revision ID: 40a11c012556
Revises: 3394654f4780
Create Date: 2015-01-30 15:20:54.550004

"""

# revision identifiers, used by Alembic.
revision = '40a11c012556'
down_revision = '3394654f4780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('query_text', sa.String(), nullable=True))
    op.drop_column('queries', 'query')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('queries', 'query_text')
    ### end Alembic commands ###
